[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "complex-visualizer"
version = "0.0.1"
description = "Complex visualizer"
dependencies = [
    "graph-visualizer-api==0.0.1",
    "jinja2==3.1.4"
]