[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "graph-visualizer-api"
version = "0.1.1"
description = "Graph visualizer API"
dependencies = []